plugins {
    id 'java'
    id 'groovy'
    id 'jacoco'
}

group = 'ru.nsu.romankin.dsl'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url 'https://repo.gradle.org/gradle/libs-releases' }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.gradle:gradle-tooling-api:8.12'
    implementation 'org.eclipse.jgit:org.eclipse.jgit:6.9.0.202403050737-r'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'com.google.guava:guava:32.1.1-jre'
    implementation 'org.apache.commons:commons-lang3:3.14.0'
    implementation 'org.codehaus.groovy:groovy-all:3.0.21'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'org.thymeleaf:thymeleaf:3.1.2.RELEASE'
    implementation 'com.puppycrawl.tools:checkstyle:10.15.0'
    implementation 'com.github.stefanbirkner:system-lambda:1.2.1'
}

sourceSets {
    main {
        groovy {
            srcDirs = ['src/main/groovy', 'src/main/java']
        }
        java {
            srcDirs()
        }
    }
}
test {
    useJUnitPlatform()
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}